languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = ""
logo = "img/logo.webp"
description = "CivSoft"
copyright = "© 2023 CivSoft LLC"

dateFormat = "2 January 2006"

[author]
  name = "CivSoft"
  image = "img/logo.png"
  headline = "Coming Soon"
  bio = "CivSoft"
  links = [
    { phone = "https://calendly.com/kyle-malloy/meeting" },
    { email = "mailto:kyle@malloy.dev" },
    { twitter = "https://twitter.com/civsoftapp" },
  ]
